name: barber_app
description: Aplicativo de agendamento para barbearia
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  url_launcher: ^6.1.10
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  flutter_svg: ^2.0.5
  lottie: ^2.3.2
  google_fonts: ^4.0.4
  flutter_launcher_icons: ^0.14.4
  flutter_dotenv: ^5.1.0
  
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true