// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

// Import the configuration file that is not committed to git
import 'firebase_options_dev.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Using environment variables or config file for sensitive data
  static final FirebaseOptions web = FirebaseOptions(
    apiKey: _getApiKey(),
    appId: FirebaseOptionsConfig.appId,
    messagingSenderId: FirebaseOptionsConfig.messagingSenderId,
    projectId: FirebaseOptionsConfig.projectId,
    authDomain: FirebaseOptionsConfig.authDomain,
    storageBucket: FirebaseOptionsConfig.storageBucket,
    measurementId: FirebaseOptionsConfig.measurementId,
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: _getApiKey(),
    appId: FirebaseOptionsConfig.appId,
    messagingSenderId: FirebaseOptionsConfig.messagingSenderId,
    projectId: FirebaseOptionsConfig.projectId,
    storageBucket: FirebaseOptionsConfig.storageBucket,
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: _getApiKey(),
    appId: FirebaseOptionsConfig.appId,
    messagingSenderId: FirebaseOptionsConfig.messagingSenderId,
    projectId: FirebaseOptionsConfig.projectId,
    storageBucket: FirebaseOptionsConfig.storageBucket,
    iosClientId: FirebaseOptionsConfig.iosClientId,
    iosBundleId: FirebaseOptionsConfig.iosBundleId,
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: _getApiKey(),
    appId: FirebaseOptionsConfig.appId,
    messagingSenderId: FirebaseOptionsConfig.messagingSenderId,
    projectId: FirebaseOptionsConfig.projectId,
    storageBucket: FirebaseOptionsConfig.storageBucket,
    iosClientId: FirebaseOptionsConfig.iosClientId,
    iosBundleId: FirebaseOptionsConfig.iosBundleId,
  );
  
  // Helper method to get API key from environment or config
  static String _getApiKey() {
    // Try to get from .env file first
    final envApiKey = dotenv.env['FIREBASE_API_KEY'];
    if (envApiKey != null && envApiKey.isNotEmpty) {
      return envApiKey;
    }
    // Fall back to config file
    return FirebaseOptionsConfig.apiKey;
  }
}