// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // NOTA: Substitua estes valores pelos valores reais do seu projeto Firebase
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:000000000000:web:xxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'barber-app-xxxxx',
    authDomain: 'barber-app-xxxxx.firebaseapp.com',
    storageBucket: 'barber-app-xxxxx.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:000000000000:android:xxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'barber-app-xxxxx',
    storageBucket: 'barber-app-xxxxx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:000000000000:ios:xxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'barber-app-xxxxx',
    storageBucket: 'barber-app-xxxxx.appspot.com',
    iosClientId: 'xxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:000000000000:ios:xxxxxxxxxxxxxxxx',
    messagingSenderId: '000000000000',
    projectId: 'barber-app-xxxxx',
    storageBucket: 'barber-app-xxxxx.appspot.com',
    iosClientId: 'xxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com',
    iosBundleId: 'com.example.barberApp',
  );
}